os: Visual Studio 2017

matrix:
  fast_finish: true

platform:
  - x64

configuration:
  - Debug
  - Release

clone_folder: c:\libwebrtc

before_build:
  - cd c:s\libwebrtc
  - set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DCMAKE_INSTALL_PREFIX=c:\libwebrtc .

build:
  project: PACKAGE.vcxproj

artifacts:
  - path: libwebrtc-*.zip
    name: Releases

deploy:
  provider: S3
  access_key_id:
    secure: 9UzCzcHa6axJAMo8navzOZcJzrofwd8rR/kZmmR1fEc=
  secret_access_key:
    secure: juuUIloppJdgPrLQZr4eSVwYuf/MK8QmaOWtjLVnIfxxqutbKsWyIA3pU/SjTJMk
  bucket: libwebrtc
  region: us-west-2
  unzip: false
  set_public: false
  artifact: Releases

test: off
